services:
  cuda_container:
    container_name: mlgroup1
    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./model:/model
      - ./src:/src
      - ./logs:/logs
    working_dir: /app
    command: python3 ./train_transformer.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
