services:
  cuda_container:
    container_name: mlgroup1
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./model:/model
    working_dir: /app
    command: python3 ./.data/transformer.py
    # deploy:
    #   resources:
    #     devices:
    #       - driver: nvidia
    #         count: 1
    #         capabilities: [gpu]
